[workspace]
members = [
    # emulator core files.
    "core/core-util",
    "core/*",
    # emulator frontend files.
    "frontend/common",
    "frontend/cores/*",
    "frontend/desktop",
]
# Required to determine version for wgpu
resolver = "2"
