[workspace]
members = [
    # Frontend code.
    "frontend",
    # Nintendo DS core.
    "cores/nds",
    # Common
    "common/arm-decode",
]
resolver = "2"

[profile.dev]
opt-level = 1
overflow-checks = true