[package]
name = "desktop"
version = "0.1.0"
edition = "2021"

[features]
nds-core = ["dep:nds-frontend"]
core-all = ["nds-core"]

default = ["core-all"]

[dependencies]
# core-frontends
nds-frontend = { path = "../cores/nds-frontend", optional = true } 

# imgui
imgui = "0.8.0"
imgui-wgpu = "0.20.0"
imgui-winit-support = { version = "0.8.2", default_features = false, features = ["winit-26"] }

#wgpu
wgpu = "0.13.0"

#winit
winit = "0.26.0"

#pollster 
pollster = "0.2.5"