[package]
name = "desktop"
version = "0.1.0"
edition = "2021"

[features]
nds-core = ["dep:nds-core"]
core-all = ["nds-core"]

logging = ["nds-core?/logging"]

default = ["core-all", "logging"]

[dependencies]
# cores
nds-core = { path = "../../core/nds-core", default_features = false, optional = true } 

# util
util = { path = "../../util" } 

# imgui
imgui = "0.8.0"
imgui-wgpu = "0.20.0"
imgui-winit-support = { version = "0.8.2", default_features = false, features = ["winit-26"] }

#wgpu
wgpu = "0.13.0"

#winit
winit = "0.26.0"

#pollster 
pollster = "0.2.5"

# File dialogue crate.
rfd = "0.8.4"