[package]
name = "bitwolf-core"
version = "0.1.0"
edition = "2021"

[dependencies]
util = {path = "../util"}
arm-decode = {path = "arm-decode"}

[build-dependencies]
arm-decode = {path = "arm-decode"}
array-init = "2.0.1"